---
# This assumes a Debian box that has been bootstraped with ./bootstrap.yml
- name: Update all packages
  hosts: all
  user: zmanji
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Update all packages to the latest version
      apt: upgrade=full
