- name: Install Nginx and configure website
  hosts: all
  user: zmanji
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Install nginx
      apt: pkg=nginx state=present

    - name: Install rsync
      apt: pkg=rsync state=present

    - name: Install certbot
      apt: pkg=certbot state=present

    - name: Install python3-certbot-nginx
      apt: pkg=python3-certbot-nginx state=present

    - name: Update nginx.conf
      copy: src=files/nginx.conf
            dest=/etc/nginx/nginx.conf

    - name: Add zameermanji nginx config
      copy: src=files/nginx-zameermanji
            dest=/etc/nginx/sites-available/zameermanji.conf

    - name: Add dhparam
      copy: src=files/dhparam.pem
            dest=/etc/nginx/dhparam.pem

    - name: remove default nginx site
      file: path=/etc/nginx/sites-enabled/default
            state=absent

    - name: Ensure config symlink to enable config
      file: src=/etc/nginx/sites-available/zameermanji.conf
            dest=/etc/nginx/sites-enabled/zameermanji.conf
            state=link
    - name: Restart Nginx
      service: name=nginx state=restarted enabled=yes
